services:
  server:
    container_name: express-server
    build:
      context: ./server
    ports:
      - 5000:5000
    environment:
      # DEVELOPMENT
      - NODE_ENV=development
      - PORT=5000

      # DATABASE
      - LOCAL_DB=mongodb://mongo-db:27017/ecommerce

      # JWT
      - JWT_SECRET=icunhr3947nyv9y9ryvanoergnv8qoiuerntvigweoirhnvuhtn7tnv934yht9pvvhapoiwehn3984v
      - JWT_EXPIRES=7d
      - COOKIE_EXPIRES=7

      # NODEMAILER
      - SMTP_HOST=smtp.mailtrap.io
      - SMTP_PORT=2525
      - SMTP_USERNAME=94bc0fe4e202d8
      - SMTP_PASSWORD=c789f20ee8fa11
      - SMTP_FROM_EMAIL=noreply@ecommerce.com
      - SMTP_FROM_NAME=E-commerce

      # STRIPE
      - STRIPE_SECRET_KEY=sk_test_51LmC82KnXA3TgAzVXxr0ymqX24crsLxuKWAjl6emeO2R3hCF3DQcNXIT7LStHiNlOWH4inNHcTeK7dyLNq2bDl8f00XImrGEi4
      - STRIPE_API_KEY=pk_test_51LmC82KnXA3TgAzVqrs00doqVxxNJaw2O7T7HkrmnYDkwCVAjD9vq8b0I3BGsV3vrnOiujv9QIQibCz74MSTHSuI00dNNzpfxj

      # CLOUDINARY
      - CLOUDINARY_CLOUD_NAME=dfmgyv4r8
      - CLOUDINARY_API_KEY=315114292999569
      - CLOUDINARY_API_SECRET=ovTRPMwjBl6fAnRSPIW477TwUqs

    volumes:
      - ./server:/app:cache
      - /app/node_modules
    networks:
      - mern-app
    depends_on:
      - mongo
    command: npm start

  client:
    container_name: react-app
    build:
      context: ./client
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./client:/app:cache
      - /app/node_modules
    networks:
      - mern-app
    depends_on:
      - server
    command: npm start

  mongo:
    container_name: mongo-db
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-app
    logging:
      driver: none

volumes:
  mongo-data:
    driver: local

networks:
  mern-app:
    driver: bridge
